use_frameworks!

platform :ios, '10.0'

target 'HXPhotoPickerKit_Example' do
  pod 'HXPhotoPickerKit', :path => '../'

  target 'HXPhotoPickerKit_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
